# Generated by Django 4.0.6 on 2022-07-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='uploads/default.jpg', upload_to='uploads/'),
        ),
    ]
